language: java
deploy:
  provider: releases
  api_key:
    secure: hDDdTLZQQJs01IEnamoxxDLdzTrN9GycS+6UME+p9XHD7wEG/IJheGD3vpEKkeNxdxG1GRLbr0HH4ICK7rA+vFtEM0sGwx7OvIvin5JSauqzIY/XoCH9DwfjNdKGDjHxPaCfGQgMZS2bzvn+UBIkk0GQ5zfmdxYOmdc3YTOZf7E=
  file: build/libs/sample-jar-1.jar
  on:
    repo: msp132/sample-jar
    all_branches: true
    tags: true


