language: java
deploy:
  provider: releases
  api_key:
    secure: OiLZg53dLTGAetc/q4oc/PgG++b9jDKr4rrbFGQlOKGd/zvY2OeosQrw/E1KSJEoPDlEhZMa5k21lvN3JlyYrranXOmlc5Muo2O8nGPrRKxJNSDCB4J1C3O59IQbCAM7N/6bWMsQ94Kfwj6m0QkIBkAQyBMQPzXCbtc9m5zhqok=
  file: build/libs/*
  on:
    repo: msp132/sample-jar
    all_branches: true
    tags: true
after_script:
  -mkdir temp
  -cd temp
  -git clone git://github.com/msp132/maven-repo.git
  -cp ../build/libs/* .
  -git add *
  -git commit -m -a "new version"
  -git push
